name: Create Issue from Form Submission

on:
  repository_dispatch:
    types: [form_submission]

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Create GitHub Issue
        uses: actions/github-script@v6
        with:
          script: |
            const payload = context.payload.client_payload;
            const issueTitle = 'New Form Submission';
            const issueBody = `Name: ${payload.name}\nEmail: ${payload.email}\nDate: ${payload.date}\nIssue Type: ${payload.issueType}\nOther: ${payload.otherText || 'N/A'}`;
            
            await github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody
            });
